import res_partner,crm_lead,fory_purchase_request,purchase_order,fory_loyalty_card,sale_order
import stock_picking,fields,res_currency,stock_return_picking,fory_coupon,pos_order
import stock_quant, fory_product_slider,stock_pack_operation,sale_make_invoice_advance
import supplier_info,fory_product_brand,product_template,fory_product_supplierinfo_import